import type { Project, Testimonial, Service, Skill, Experience, SiteSettings } from '@/types';

export const siteSettings: SiteSettings = {
  name: 'Md Najmul Hasan Tosif',
  title: 'UI/UX & Graphic Designer',
  tagline: 'Crafting Digital Experiences That Inspire',
  description: 'Award-winning UI/UX and Graphic Designer specializing in premium digital products, brand identities, and motion-rich interfaces.',
  email: 'tosif@design.studio',
  location: 'Available Worldwide',
  availability: 'Open to Projects',
  social_links: {
    twitter: 'https://twitter.com',
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    dribbble: 'https://dribbble.com',
    behance: 'https://behance.net',
  },
  seo: {
    title: 'Tosif — UI/UX & Graphic Designer',
    description: 'Award-winning designer crafting premium digital experiences.',
    keywords: ['UI/UX Design', 'Graphic Design', 'Product Design', 'Branding'],
  },
  sections_order: ['hero', 'projects', 'services', 'about', 'testimonials', 'contact'],
  sections_enabled: {
    hero: true,
    projects: true,
    services: true,
    about: true,
    testimonials: true,
    contact: true,
  },
};

export const projects: Project[] = [
  {
    id: '1',
    title: 'Nexus Banking',
    slug: 'nexus-banking',
    tagline: 'The future of personal finance',
    description: 'A next-generation banking app redesign with AI-powered insights, biometric auth, and real-time portfolio management.',
    category: 'UI/UX Design',
    tags: ['Fintech', 'Mobile', 'iOS', 'Product Design'],
    thumbnail: '/projects/nexus-banking.jpg',
    hero_image: '/projects/nexus-banking-hero.jpg',
    images: [],
    case_study: {
      overview: 'Complete redesign of a banking platform serving 2M+ users, focusing on simplicity and trust.',
      problem: 'Users found the existing interface confusing, leading to high drop-off rates during onboarding.',
      research: 'Conducted 50+ user interviews, competitive analysis, and usability testing sessions.',
      user_journey: 'Mapped complete user journeys from onboarding to daily banking tasks.',
      wireframes: [],
      design_system: {
        colors: [{ name: 'Primary', hex: '#6366f1' }, { name: 'Surface', hex: '#0a0a0a' }],
        typography: [{ name: 'Inter', usage: 'Body & UI' }],
        components: ['Button', 'Card', 'Input', 'Chart'],
      },
      results: '340% increase in user engagement, 78% reduction in support tickets.',
      duration: '6 months',
      role: 'Lead Product Designer',
      tools: ['Figma', 'Principle', 'After Effects'],
    },
    status: 'published',
    featured: true,
    order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: '2',
    title: 'Orbit Design System',
    slug: 'orbit-design-system',
    tagline: 'Scalable design at enterprise level',
    description: 'A comprehensive design system built for a Fortune 500 tech company, enabling 200+ designers to work cohesively.',
    category: 'Design Systems',
    tags: ['Design System', 'Figma', 'Documentation', 'Enterprise'],
    thumbnail: '/projects/orbit-ds.jpg',
    hero_image: '/projects/orbit-ds-hero.jpg',
    images: [],
    case_study: {
      overview: 'Built from scratch — tokens, components, patterns, and documentation for enterprise scale.',
      problem: 'Inconsistent UI across 15 product teams causing poor user experience and slow development.',
      research: 'Audited 3,000+ existing UI elements across all products to identify patterns.',
      user_journey: 'Designer and developer workflows mapped to reduce friction.',
      wireframes: [],
      design_system: {
        colors: [{ name: 'Blue', hex: '#3b82f6' }, { name: 'Dark', hex: '#09090b' }],
        typography: [{ name: 'Geist', usage: 'System UI' }],
        components: ['200+ Components', 'Tokens', 'Patterns', 'Icons'],
      },
      results: '60% faster design-to-dev handoff, adopted by 200+ designers globally.',
      duration: '8 months',
      role: 'Design System Lead',
      tools: ['Figma', 'Storybook', 'Zeroheight'],
    },
    status: 'published',
    featured: true,
    order: 2,
    created_at: '2024-02-01',
    updated_at: '2024-08-01',
  },
  {
    id: '3',
    title: 'Aura Brand Identity',
    slug: 'aura-brand-identity',
    tagline: 'Where luxury meets sustainability',
    description: 'Complete brand identity for a luxury sustainable fashion label — logo, typography, packaging, and digital presence.',
    category: 'Branding',
    tags: ['Branding', 'Logo', 'Packaging', 'Print'],
    thumbnail: '/projects/aura-brand.jpg',
    hero_image: '/projects/aura-brand-hero.jpg',
    images: [],
    case_study: {
      overview: 'Full brand identity from naming to packaging for a premium sustainable fashion startup.',
      problem: 'New brand needed to communicate both luxury and environmental responsibility — a rare balance.',
      research: 'Deep competitor analysis in luxury fashion and sustainable brands.',
      user_journey: 'Customer touchpoints from discovery to purchase mapped.',
      wireframes: [],
      design_system: {
        colors: [{ name: 'Sage', hex: '#87a878' }, { name: 'Cream', hex: '#f5f0e8' }],
        typography: [{ name: 'Canela', usage: 'Display' }, { name: 'Neue Montreal', usage: 'Body' }],
        components: ['Logo Suite', 'Pattern Library', 'Packaging'],
      },
      results: 'Brand launched to 50K+ Instagram followers on day one. Featured in Vogue.',
      duration: '3 months',
      role: 'Brand Designer',
      tools: ['Illustrator', 'Photoshop', 'InDesign'],
    },
    status: 'published',
    featured: true,
    order: 3,
    created_at: '2024-03-01',
    updated_at: '2024-07-01',
  },
  {
    id: '4',
    title: 'Pulse Analytics',
    slug: 'pulse-analytics',
    tagline: 'Data made beautiful and actionable',
    description: 'SaaS analytics dashboard for marketing teams with real-time data visualization and AI-driven recommendations.',
    category: 'Dashboard Design',
    tags: ['SaaS', 'Dashboard', 'Data Viz', 'Web App'],
    thumbnail: '/projects/pulse-analytics.jpg',
    hero_image: '/projects/pulse-analytics-hero.jpg',
    images: [],
    case_study: {
      overview: 'Marketing analytics platform redesigned for clarity, speed, and actionability.',
      problem: 'Complex data was overwhelming users — they couldn\'t derive insights quickly.',
      research: 'Interviewed 30 marketing managers about their data needs and pain points.',
      user_journey: 'Mapped the journey from raw data to business decision.',
      wireframes: [],
      design_system: {
        colors: [{ name: 'Violet', hex: '#8b5cf6' }, { name: 'Dark Surface', hex: '#0f0f12' }],
        typography: [{ name: 'Plus Jakarta', usage: 'UI & Data' }],
        components: ['Charts', 'KPI Cards', 'Filters', 'Tables'],
      },
      results: '2.4x faster insight discovery. NPS improved from 32 to 71.',
      duration: '5 months',
      role: 'Product & UX Designer',
      tools: ['Figma', 'Principle', 'Lottie'],
    },
    status: 'published',
    featured: false,
    order: 4,
    created_at: '2024-04-01',
    updated_at: '2024-09-01',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    role: 'CPO',
    company: 'TechVault Inc.',
    avatar: '',
    content: 'Tosif delivered an exceptional product design that transformed our user experience. The attention to detail, motion design, and overall quality was outstanding. Our conversion rate increased by 240% after the redesign.',
    rating: 5,
    featured: true,
    order: 1,
  },
  {
    id: '2',
    name: 'Marcus Williams',
    role: 'Founder & CEO',
    company: 'Orbital Labs',
    avatar: '',
    content: 'Working with Tosif was the best design decision we made. He doesn\'t just design interfaces — he engineers experiences. The design system he built scaled beautifully across our entire product suite.',
    rating: 5,
    featured: true,
    order: 2,
  },
  {
    id: '3',
    name: 'Amelia Rodriguez',
    role: 'Head of Brand',
    company: 'Aura Studio',
    avatar: '',
    content: 'Our brand identity exceeded every expectation. Tosif has a rare ability to balance aesthetics with strategy. The work he created for us was truly world-class and helped us secure our Series A.',
    rating: 5,
    featured: true,
    order: 3,
  },
  {
    id: '4',
    name: 'James Park',
    role: 'VP of Product',
    company: 'NovaSaaS',
    avatar: '',
    content: 'Incredible talent. Tosif redesigned our entire dashboard and the results speak for themselves — engagement is up 180% and churn dropped significantly. Highly recommend for any serious design project.',
    rating: 5,
    featured: true,
    order: 4,
  },
  {
    id: '5',
    name: 'Priya Nair',
    role: 'Creative Director',
    company: 'PixelHive',
    avatar: '',
    content: 'A genuinely world-class designer. The motion design and interactions Tosif brought to our product made it feel like a premium tool. Our users constantly comment on how beautiful it is.',
    rating: 5,
    featured: true,
    order: 5,
  },
];

export const services: Service[] = [
  {
    id: '1',
    title: 'UI Design',
    description: 'Pixel-perfect interfaces with premium aesthetics, micro-interactions, and design systems built for scale.',
    icon: 'Layers',
    features: ['Component Libraries', 'Design Tokens', 'Responsive Design', 'Accessibility'],
    enabled: true,
    order: 1,
  },
  {
    id: '2',
    title: 'UX Design',
    description: 'Human-centered research, user journeys, wireframes, and prototypes that solve real problems.',
    icon: 'Users',
    features: ['User Research', 'Journey Mapping', 'Wireframing', 'Usability Testing'],
    enabled: true,
    order: 2,
  },
  {
    id: '3',
    title: 'Product Design',
    description: 'End-to-end product design from concept to launch, combining strategy, UX, and visual design.',
    icon: 'Cpu',
    features: ['Product Strategy', 'MVP Design', 'Iteration Cycles', 'Stakeholder Alignment'],
    enabled: true,
    order: 3,
  },
  {
    id: '4',
    title: 'Branding',
    description: 'Complete brand identities — logos, typography, color systems, and brand guidelines.',
    icon: 'Sparkles',
    features: ['Logo Design', 'Brand Guidelines', 'Color Systems', 'Typography'],
    enabled: true,
    order: 4,
  },
  {
    id: '5',
    title: 'Motion Design',
    description: 'Expressive animations, micro-interactions, and motion systems that bring interfaces to life.',
    icon: 'Play',
    features: ['UI Animations', 'Lottie Files', 'Video Production', 'Interaction Design'],
    enabled: true,
    order: 5,
  },
  {
    id: '6',
    title: 'Design Systems',
    description: 'Scalable, documented design systems that enable teams to build consistent products faster.',
    icon: 'Grid',
    features: ['Token Architecture', 'Component Documentation', 'Figma Libraries', 'Dev Handoff'],
    enabled: true,
    order: 6,
  },
  {
    id: '7',
    title: 'Graphic Design',
    description: 'Print and digital graphic design — presentations, social media, marketing materials.',
    icon: 'Pen',
    features: ['Print Design', 'Social Media', 'Presentations', 'Marketing Assets'],
    enabled: true,
    order: 7,
  },
  {
    id: '8',
    title: 'Landing Pages',
    description: 'High-converting, visually stunning landing pages designed to turn visitors into customers.',
    icon: 'Monitor',
    features: ['Conversion Optimization', 'A/B Testing', 'Mobile-First', 'SEO Ready'],
    enabled: true,
    order: 8,
  },
  {
    id: '9',
    title: 'Dashboard Design',
    description: 'Complex data visualization and dashboard design that makes information intuitive and actionable.',
    icon: 'BarChart',
    features: ['Data Visualization', 'KPI Design', 'Filter Systems', 'Real-time UI'],
    enabled: true,
    order: 9,
  },
];

export const skills: Skill[] = [
  { id: '1', name: 'Figma', category: 'Design Tools', level: 98 },
  { id: '2', name: 'Adobe XD', category: 'Design Tools', level: 92 },
  { id: '3', name: 'Illustrator', category: 'Design Tools', level: 95 },
  { id: '4', name: 'Photoshop', category: 'Design Tools', level: 94 },
  { id: '5', name: 'After Effects', category: 'Motion', level: 88 },
  { id: '6', name: 'Principle', category: 'Prototyping', level: 85 },
  { id: '7', name: 'Framer', category: 'Design Tools', level: 90 },
  { id: '8', name: 'Webflow', category: 'No-Code', level: 82 },
  { id: '9', name: 'User Research', category: 'UX Skills', level: 94 },
  { id: '10', name: 'Design Systems', category: 'UX Skills', level: 96 },
  { id: '11', name: 'Prototyping', category: 'UX Skills', level: 92 },
  { id: '12', name: 'Typography', category: 'Design Skills', level: 97 },
];

export const experience: Experience[] = [
  {
    id: '1',
    company: 'TechVault Inc.',
    role: 'Senior Product Designer',
    description: 'Led design for 3 major product lines, built a design system adopted by 50+ engineers, and drove a 240% increase in key conversion metrics.',
    start_date: '2023-01',
    current: true,
    achievements: ['Built Orbit Design System', 'Led team of 5 designers', 'Increased conversion 240%'],
  },
  {
    id: '2',
    company: 'Orbital Labs',
    role: 'UI/UX Designer',
    description: 'Designed mobile-first SaaS products for fintech and healthtech clients. Specialized in complex data visualization and onboarding flows.',
    start_date: '2021-06',
    end_date: '2022-12',
    current: false,
    achievements: ['Designed 12 products from 0→1', 'User satisfaction +89%', 'Featured on Behance'],
  },
  {
    id: '3',
    company: 'Freelance',
    role: 'Brand & UI Designer',
    description: 'Worked with 30+ startups and agencies across branding, UI design, and marketing design. Built long-term client relationships globally.',
    start_date: '2019-01',
    end_date: '2021-05',
    current: false,
    achievements: ['30+ global clients', '5-star rated on Upwork', '$500K+ revenue generated for clients'],
  },
];
